name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:

    runs-on: ubuntu-latest

    steps:   
    - uses: actions/checkout@v2
    
    - name: install google tests for c++
      run: sudo apt-get install libgtest-dev
      
    - name: compile binary 
      run: make compile

    - name: Upload artifact 
      uses: actions/upload-artifact@v2
      with:
        name: main
        path: ./main
        
  test:
    runs-on: ubuntu-latest
    needs: compile

    steps:
      - uses: actions/checkout@v2
      
      - name: install google tests for c++
        run: sudo apt-get install libgtest-dev
      
      - name: Download binary file
        uses: actions/download-artifact@v2
        with:
          name: main
          
      - name: run tests
        run: | 
          chmod 111 main
          ./main
          
          
